# This file is where you keep secret settings, passwords, and tokens!
# If you put them in the code you risk committing that info or sharing it
# DO NOT EDIT THIS FILE AND UPLOAD IT TO GITHUB!

secrets = {
    'ssid' : 'GL-MT300N-V2-35c',
    'password' : 'goodlife',
    'timezone' : "America/New_York", # http://worldtimeapi.org/timezones
    }
