# This file is where you keep secret settings, passwords, and tokens!
# If you put them in the code you risk committing that info or sharing it
# DO NOT EDIT THIS FILE AND UPLOAD IT TO GITHUB!

secrets = {
    'ssid' : 'Julian Network',
    'password' : '(julito74@R$N)',
    'aio_username' : 'my_adafruit_io_username',
    'aio_key' : 'my_adafruit_io_key',
    'timezone' : "America/New_York", # http://worldtimeapi.org/timezones
    }
